queues:
  - [default, 1]
  - [webhooks, 1]
  - [sms, 2]
  - [images, 1]
  - [mailers, 1]
  - [recurrent, 1]
  - [rollbar, 1]

production:
  :concurrency: <%= ENV.fetch('SIDEKIQ_THREADS', 10) %>
  :max_retries: 3
